server:
  port: 8080

spring:
  application:
     name: spring-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: path_route
        uri: http://127.0.0.1:8081
        predicates:
        - Path=/test/**
