spring:
  application:
     name: spring-cloud-gateway-demo
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.11.233:8849
        namespace: zhs
      config:
        namespace: zhs

nacos:
  address: 172.20.11.233:8849
  data-id: spring-cloud-gateway-demo.yaml
  group-id: DEFAULT_GROUP
  timeout: 5000
