server:
  port: 8080

spring:
  application:
     name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://127.0.0.1:8081/hello
        predicates:
        - Path=/hello
