server:
  port: 8081

spring:
  application:
     name: spring-boot-test
  cloud:
    nacos:
      discovery:
        server-addr: 172.20.11.233:8849
        namespace: zhs
      config:
        namespace: zhs


